
<?php if ($namespace): ?>
namespace <?php echo $namespace ?>;
<?php endif ?>

<?php if (count($imports) > 0): ?>
<?php foreach ($imports as $import): ?>
<?php if ($namespace || false !== strpos($import, '\\')): ?>
use <?php echo $import ?>;
<?php endif ?>
<?php endforeach ?>
<?php endif ?>

/**
 * Creates Puli's core services.
 *
 * This class was auto-generated by Puli.
 *
 * IMPORTANT: Before modifying the code below, set the "factory.auto-generate"
 * configuration key to false:
 *
 *     $ puli config factory.auto-generate false
 *
 * Otherwise any modifications will be overwritten!
 */
class <?php echo $shortClassName ?> implements <?php echo $factoryInterfaceName ?>
{
    /**
     * Creates the resource repository.
     *
     * @return ResourceRepository The created resource repository.
     */
    public function createRepository()
    {
<?php foreach ($repoDeclarations as $declaration): ?>
<?php echo $this->indent($declaration, 8)."\n\n" ?>
<?php endforeach ?>
        return <?php echo $repoVarName ?>;
    }

    /**
     * Creates the resource discovery.
     *
     * @param ResourceRepository <?php echo $repoVarName ?> The resource repository to read from.
     *
     * @return ResourceDiscovery The created resource discovery.
     */
    public function createDiscovery(ResourceRepository <?php echo $repoVarName ?>)
    {
<?php foreach ($discoveryDeclarations as $declaration): ?>
<?php echo $this->indent($declaration, 8)."\n\n" ?>
<?php endforeach ?>
        return <?php echo $discoveryVarName ?>;
    }
}
